version: 1.0
name: CryoPersistence
main: me.cryocell.cryopersistence.CryoPersistence
author: cryocell
api-version: '1.13'
description: Automatic World Backups/Saves
commands:
  cryo-persist:
    description: Automatic World Backup/Save Command.
    usage: /cryo-persist <args> [args]
    aliases: [cp, cpersist]
permissions:
  cryo-persist.admin.reload:
    default: op
  cryo-persist.admin.fbackup:
    default: op
  cryo-persist.admin.fsave:
    default: op
  cryo-persist.help:
    default: true
  cryo-persist.version:
    default: true